theme: jekyll-theme-minimal
title: Thomas Gorman's Homepage
description: Updates and descriptions of Thomas Gorman's projects
logo: image/https://github.com/tmgorman23/tmgorman23.github.io/blob/main/drip.jpg?raw=true
