theme: jekyll-theme-minimal
title: Thomas Gorman's Homepage
logo: "/images/drip.jpg?raw=true"
description: > Updates and descriptions of change Thomas Gorman's projects
               <br><br>
               Twitter
               <br>
               <a href="https://twitter.com/ThomasG047">My profile</a>
